on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run"
        required: true
        type: boolean
jobs:
  vsce-test:
    strategy:
      matrix:
        target: [linux-x64, linux-arm64, darwin-x64, darwin-arm64]
    name: Deploy Extension
    runs-on: ubunut-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - uses: "aws-actions/configure-aws-credentials@v1"
        with:
          role-to-assume: "arn:aws:iam::338683922796:role/returntocorp-semgrep-vscode-deploy-role"
          role-duration-seconds: 900,
          role-session-name: "semgrep-vscode-deploy"
          aws-region: "us-west-2"
      - name: download osemgrep pro
        run: ./download-osemgrep-pro.sh ${{ matrix.target }}
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1.6.2
        id: publishToOpenVSX
        with:
          # Tied to austin@, lives in 1password, does not expire
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          target: ${{ matrix.target }} # only for specific platforms
          dryRun: ${{ github.event.inputs.dry-run }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1.6.2
        with:
          # Tied to bence@, lives in 1password expires in may 2024
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          target: ${{ matrix.target }}
          dryRun: ${{ github.event.inputs.dry-run }}
