name: tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - develop
    paths-ignore:
      - "**.md"

jobs:
  vsce-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Semgrep
        run: python -m pip install semgrep
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install dependencies
        run: npm ci
      # This will be needed when we add in windows testing
      #- name: configure npm
      #  if: runner.os == 'Windows'
      #  run: npm config set script-shell "C:\\Program Files\\Git\\Bin\\bash.exe"
      - name: pretest
        run: npm run pretest
      - name: run native tests (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run -a npm test-native
      - name: run native tests (MacOS)
        if: matrix.os == 'macos-latest'
        run: npm test-native
      - name: uninstall semgrep
        run: python -m pip uninstall semgrep
      - name: run js tests (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run -a npm test-js
      - name: run js tests (MacOS)
        if: matrix.os == 'macos-latest'
        run: npm test-js

  vsce-prepublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run vscode:prepublish
